vars:
  - raw_path: '/media/sf_linux-ext/pica'
  - dump_path: 'dump'
  - filter_path: 'filter'
  - abzug_path: 'abzug'

stages:
  prepare:
    cmd: pica filter -s -g "017A.a =^ 'yy' || 209A/*.f =^ 'DBSM'" ${raw_path}/DNBtitelundexemplare.dat.gz -o ${dump_path}/dbsm-titel-exemplare.dat.gz
    deps:
      - ${raw_path}/DNBtitelundexemplare.dat.gz
    outs:
      - ${dump_path}/dbsm-titel-exemplare.dat.gz
  
  filter:
    cmd:
      - pica filter "209A/*.a =^ 'Bö M' || 209A/*.g =^ 'Bö M' || 209A/*.a =^ 'Boe M' || 209A/*.g =^ 'Boe M'" ${dump_path}/dbsm-titel-exemplare.dat.gz | pica select --translit nfc "003@.0,002@.0,021A{a,d},021A{Y?,Y},021B{l,a},039D.9,039I.9,039B.9,036H{9,g}" -H "idn,bbg,tit_a, tit_d, tit_Y,stuecktitel_l,stuecktitel_a, f4243,f4256,f4241,f4105_9,f4105_g" -o ${filter_path}/böm-titel.csv
      
      - pica filter --reduce "003@,209A,209C,247C,237A,101@" "209A/*.a =^ 'Bö M' || 209A/*.g =^ 'Bö M' || 209A/*.a =^ 'Boe M' || 209A/*.g =^ 'Boe M'" ${dump_path}/dbsm-titel-exemplare.dat.gz | pica print --translit nfc -o ${filter_path}/böm-exemplare.dat

      - pica filter "209A/*.a =^ 'Bö Ink' || 209A/*.g =^ 'Bö Ink'" ${dump_path}/dbsm-titel-exemplare.dat.gz | pica select --translit nfc "003@.0,002@.0,021A{a,d},021A{Y?,Y},021B{l,a},039D.9,039I.9,039B.9,036H{9,g}" -H "idn,bbg,tit_a, tit_d, tit_Y,stuecktitel_l,stuecktitel_a, f4243,f4256,f4241,f4105_9,f4105_g" -o ${filter_path}/böink-titel.csv
      
      - pica filter --reduce "003@,209A,209C,247C,237A,101@" "209A/*.a =^ 'Bö Ink' || 209A/*.g =^ 'Bö Ink'" ${dump_path}/dbsm-titel-exemplare.dat.gz | pica print --translit nfc -o ${filter_path}/böink-exemplare.dat

      - pica filter "209A/*.a =^ 'II' && 044P/*.9 == '040270416'" ${dump_path}/dbsm-titel-exemplare.dat.gz | pica select --translit nfc "003@.0,002@.0,021A{a,d},021A{Y?,Y},021B{l,a},039D.9,039I.9,039B.9,036H{9,g}" -H "idn,bbg,tit_a, tit_d, tit_Y,stuecktitel_l,stuecktitel_a, f4243,f4256,f4241,f4105_9,f4105_g" -o ${filter_path}/ii-titel.csv
      
      - pica filter --reduce "003@,209A,209C,247C,237A,101@" "209A/*.a =^ 'II' && 044P/*.9 == '040270416'" ${dump_path}/dbsm-titel-exemplare.dat.gz | pica print --translit nfc -o ${filter_path}/ii-exemplare.dat

      - pica filter "209A/*.a =^ 'III'" ${dump_path}/dbsm-titel-exemplare.dat.gz | pica select --translit nfc "003@.0,002@.0,021A{a,d},021A{Y?,Y},021B{l,a},039D.9,039I.9,039B.9,036H{9,g}" -H "idn,bbg,tit_a, tit_d, tit_Y,stuecktitel_l,stuecktitel_a, f4243,f4256,f4241,f4105_9,f4105_g" -o ${filter_path}/iii-titel.csv
      
      - pica filter --reduce "003@,209A,209C,247C,237A,101@" "209A/*.a =^ 'III'" ${dump_path}/dbsm-titel-exemplare.dat.gz | pica print --translit nfc -o ${filter_path}/iii-exemplare.dat

      - pica filter "209A/*.a =^ 'IV'" ${dump_path}/dbsm-titel-exemplare.dat.gz | pica select --translit nfc "003@.0,002@.0,011@.a,021A{a,d},021A{Y?,Y},021B{l,a},039D.9,039I.9,039B.9,036H{9,g}" -H "idn,bbg,jahr,tit_a, tit_d, tit_Y,stuecktitel_l,stuecktitel_a, f4243,f4256,f4241,f4105_9,f4105_g" -o ${filter_path}/iv-titel.csv
      
      - pica filter --reduce "003@,209A,209C,247C,237A,101@" "209A/*.a =^ 'IV'" ${dump_path}/dbsm-titel-exemplare.dat.gz | pica print --translit nfc -o ${filter_path}/iv-exemplare.dat

      - pica filter "044P/*.9 == '041799844'" ${dump_path}/dbsm-titel-exemplare.dat.gz | pica select --translit nfc "003@.0,002@.0,011@.a,021A{a,d},021A{Y?,Y},021B{l,a},039D.9,039I.9,039B.9,036H{9,g}" -H "idn,bbg,jahr,tit_a, tit_d, tit_Y,stuecktitel_l,stuecktitel_a, f4243,f4256,f4241,f4105_9,f4105_g" -o ${filter_path}/schreibmeister-titel.csv

      - pica filter --reduce "003@,209A,209C,247C,237A,101@" "044P/*.9 == '041799844' && 011@.a =~ '^([01xX][0-7x][0-9xX][0-9xX])|([01xX][8][12][0-9xX])|([01xX][8][3][0])'" ${dump_path}/dbsm-titel-exemplare.dat.gz | pica print --translit nfc -o ${filter_path}/schreibmeister-exemplare.dat

    deps:
      - ${dump_path}/dbsm-titel-exemplare.dat.gz
    
    outs:
      - ${filter_path}/böm-titel.csv
      - ${filter_path}/böm-exemplare.dat
      - ${filter_path}/böink-titel.csv
      - ${filter_path}/böink-exemplare.dat
      - ${filter_path}/ii-titel.csv
      - ${filter_path}/ii-exemplare.dat
      - ${filter_path}/iii-titel.csv
      - ${filter_path}/iii-exemplare.dat
      - ${filter_path}/iv-titel.csv
      - ${filter_path}/iv-exemplare.dat
      - ${filter_path}/schreibmeister-titel.csv
      - ${filter_path}/schreibmeister-exemplare.dat
  abzug:
    cmd: 
      - python ./skripte/abzug.py

    deps:
      - ${filter_path}/böm-titel.csv
      - ${filter_path}/böm-exemplare.dat
      - ${filter_path}/böink-titel.csv
      - ${filter_path}/böink-exemplare.dat
      - ${filter_path}/ii-titel.csv
      - ${filter_path}/ii-exemplare.dat
      - ${filter_path}/iii-titel.csv
      - ${filter_path}/iii-exemplare.dat
      - ${filter_path}/iv-titel.csv
      - ${filter_path}/iv-exemplare.dat
      - ${filter_path}/schreibmeister-titel.csv
      - ${filter_path}/schreibmeister-exemplare.dat
    
    outs:
      - ${abzug_path}/böm.csv
      - ${abzug_path}/böink.csv
      - ${abzug_path}/ii.csv
      - ${abzug_path}/iii.csv
      - ${abzug_path}/iv.csv
      - ${abzug_path}/schreibmeister.csv