vars:
  - raw_path: 'raw'
  - dump_path: 'dump'
  - filter_path: 'filter'
  - abzug_path: 'abzug'

stages:
  # der Gesamtabzug der DNB-Daten wird auf DBSM-Daten reduziert
  prepare:
    cmd:
      - |
        if [ ! -d "dump/" ]; then
          mkdir dump
        fi
      - |
        if [ ! -d "filter/" ]; then
          mkdir filter
        fi
      - |
        if [ ! -d "abzug/" ]; then
          mkdir abzug
        fi
      - pica filter -s -g "017A.a =^ 'yy' || 209A/*.f =^ 'DBSM' || 247C/*.9 == '009033645'" ${raw_path}/DNBtitelundexemplare.dat.gz -o ${dump_path}/dbsm-titel-exemplare.dat.gz
    
    deps:
      - ${raw_path}/DNBtitelundexemplare.dat.gz
    
    outs:
      - ${dump_path}/dbsm-titel-exemplare.dat.gz
  
  filter:
    cmd:
      # Für jeden Teilbestand werden zwei Suchläufe unternommen. Der erste liest Felder aus den Titeldaten direkt in eine csv-Datei. Der zweite liest Felder aus den Exemplardaten in eine .dat-Datei, die dann im Schritt "abzug" von Python gefiltert wird, um die notwendigen Exemplardaten auszulesen.

      # Das ö (Umlaut o) ist hier Unicode decomposed, d.h. ein Druck auf die Taste Ö auf der Tastatur produziert nicht das Zeichen, das im Filterausdruck steht. Hängt damit zusammen, dass der Dump in dieser Codierung geliefert wird. Bei den ausgegebenen Daten in der csv bzw dat ist das kein Problem, weil das mit der Option --translit nfc in Unicode-Normalform überführt wird. D.h. in allen weiteren Schritten können die normalen, über die Tastatur erreichbaren Umlaute genutzt werden. Dürfte nur hier beim Ö relevant sein.

      # Wenn der Filterausdruck im Titeldurchgang geändert wird, muss er auch im Exemplarlauf geändert werden.

      - pica filter "209A/*.a =^ 'Bö M' || 209A/*.g =^ 'Bö M' || 209A/*.a =^ 'Boe M' || 209A/*.g =^ 'Boe M'" ${dump_path}/dbsm-titel-exemplare.dat.gz | pica select --translit nfc "003@.0,002@.0,021A{a,d},021A{Y?,Y},034D.a,021B{l,a},039D.9,039I.9,039B.9,036H{9,g}" -H "idn,bbg,tit_a, tit_d, tit_Y,umfang,stuecktitel_l,stuecktitel_a, f4243,f4256,f4241,f4105_9,f4105_g" -o ${filter_path}/böm-titel.csv
      
      - pica filter --reduce "003@,209A,209C,247C,237A,101@,220C" "209A/*.a =^ 'Bö M' || 209A/*.g =^ 'Bö M' || 209A/*.a =^ 'Boe M' || 209A/*.g =^ 'Boe M'" ${dump_path}/dbsm-titel-exemplare.dat.gz | pica print --translit nfc -o ${filter_path}/böm-exemplare.dat

      - pica filter "209A/*.a =^ 'Bö Ink' || 209A/*.g =^ 'Bö Ink'" ${dump_path}/dbsm-titel-exemplare.dat.gz | pica select --translit nfc "003@.0,002@.0,021A{a,d},021A{Y?,Y},034D.a,021B{l,a},039D.9,039I.9,039B.9,036H{9,g}" -H "idn,bbg,tit_a, tit_d, tit_Y,umfang,stuecktitel_l,stuecktitel_a, f4243,f4256,f4241,f4105_9,f4105_g" -o ${filter_path}/böink-titel.csv
      
      - pica filter --reduce "003@,209A,209C,247C,237A,101@,220C" "209A/*.a =^ 'Bö Ink' || 209A/*.g =^ 'Bö Ink'" ${dump_path}/dbsm-titel-exemplare.dat.gz | pica print --translit nfc -o ${filter_path}/böink-exemplare.dat

      - pica filter "209A/*.a =~ '^II[\\\s\\\d]'" ${dump_path}/dbsm-titel-exemplare.dat.gz | pica select --translit nfc "003@.0,002@.0,021A{a,d},021A{Y?,Y},034D.a,021B{l,a},039D.9,039I.9,039B.9,036H{9,g}" -H "idn,bbg,tit_a, tit_d, tit_Y,umfang,stuecktitel_l,stuecktitel_a, f4243,f4256,f4241,f4105_9,f4105_g" -o ${filter_path}/ii-titel.csv
      
      - pica filter --reduce "003@,209A,209C,247C,237A,101@,220C" "209A/*.a =~ '^II[\\\s\\\d]'" ${dump_path}/dbsm-titel-exemplare.dat.gz | pica print --translit nfc -o ${filter_path}/ii-exemplare.dat

      - pica filter "209A/*.a =^ 'III'" ${dump_path}/dbsm-titel-exemplare.dat.gz | pica select --translit nfc "003@.0,002@.0,021A{a,d},021A{Y?,Y},034D.a,021B{l,a},039D.9,039I.9,039B.9,036H{9,g}" -H "idn,bbg,tit_a, tit_d, tit_Y, umfang, stuecktitel_l,stuecktitel_a, f4243,f4256,f4241,f4105_9,f4105_g" -o ${filter_path}/iii-titel.csv
      
      - pica filter --reduce "003@,209A,209C,247C,237A,101@,220C" "209A/*.a =^ 'III'" ${dump_path}/dbsm-titel-exemplare.dat.gz | pica print --translit nfc -o ${filter_path}/iii-exemplare.dat

      - pica filter "209A/*.a =^ 'IV'" ${dump_path}/dbsm-titel-exemplare.dat.gz | pica select --translit nfc "003@.0,002@.0,011@.a,021A{a,d},021A{Y?,Y},034D.a,021B{l,a},039D.9,039I.9,039B.9,036H{9,g}" -H "idn,bbg,jahr,tit_a, tit_d, tit_Y, umfang, stuecktitel_l,stuecktitel_a, f4243,f4256,f4241,f4105_9,f4105_g" -o ${filter_path}/iv-titel.csv
      
      - pica filter --reduce "003@,209A,209C,247C,237A,101@,220C" "209A/*.a =^ 'IV'" ${dump_path}/dbsm-titel-exemplare.dat.gz | pica print --translit nfc -o ${filter_path}/iv-exemplare.dat

      - pica filter "044P/*.9 == '041799844'" ${dump_path}/dbsm-titel-exemplare.dat.gz | pica select --translit nfc "003@.0,002@.0,011@.a,021A{a,d},021A{Y?,Y},034D.a,021B{l,a},039D.9,039I.9,039B.9,036H{9,g}" -H "idn,bbg,jahr,tit_a, tit_d, tit_Y,umfang,stuecktitel_l,stuecktitel_a, f4243,f4256,f4241,f4105_9,f4105_g" -o ${filter_path}/schreibmeister-titel.csv

      - pica filter --reduce "003@,209A,209C,247C,237A,101@,220C" "044P/*.9 == '041799844'" ${dump_path}/dbsm-titel-exemplare.dat.gz | pica print --translit nfc -o ${filter_path}/schreibmeister-exemplare.dat

    deps:
      - ${dump_path}/dbsm-titel-exemplare.dat.gz
    
    outs:
      - ${filter_path}/böm-titel.csv
      - ${filter_path}/böm-exemplare.dat
      - ${filter_path}/böink-titel.csv
      - ${filter_path}/böink-exemplare.dat
      - ${filter_path}/ii-titel.csv
      - ${filter_path}/ii-exemplare.dat
      - ${filter_path}/iii-titel.csv
      - ${filter_path}/iii-exemplare.dat
      - ${filter_path}/iv-titel.csv
      - ${filter_path}/iv-exemplare.dat
      - ${filter_path}/schreibmeister-titel.csv
      - ${filter_path}/schreibmeister-exemplare.dat
  
  abzug:
    cmd: 
      - python ./skripte/abzug.py

    deps:
      - skripte/abzug.py
      - ${filter_path}/böm-titel.csv
      - ${filter_path}/böm-exemplare.dat
      - ${filter_path}/böink-titel.csv
      - ${filter_path}/böink-exemplare.dat
      - ${filter_path}/ii-titel.csv
      - ${filter_path}/ii-exemplare.dat
      - ${filter_path}/iii-titel.csv
      - ${filter_path}/iii-exemplare.dat
      - ${filter_path}/iv-titel.csv
      - ${filter_path}/iv-exemplare.dat
      - ${filter_path}/schreibmeister-titel.csv
      - ${filter_path}/schreibmeister-exemplare.dat
      - blacklist.txt
    
    outs:
      - ${abzug_path}/böm.csv
      - ${abzug_path}/böink.csv
      - ${abzug_path}/ii.csv
      - ${abzug_path}/iii.csv
      - ${abzug_path}/iv.csv
      - ${abzug_path}/schreibmeister.csv
      - ${abzug_path}/schreibmeister.xlsx
      - ${abzug_path}/iv.xlsx
      - ${abzug_path}/böm.xlsx
      - ${abzug_path}/böink.xlsx
      - ${abzug_path}/ii.xlsx
      - ${abzug_path}/iii.xlsx
